[package]
name = "garch_monte_carlo"
version = "0.1.0"
edition = "2021"

[lib]
name = "garch_monte_carlo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rayon = "1.8"
rand = "0.8"
rand_xoshiro = "0.6"
